### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by brourke228** [mvdevs/jk2mv#100]
Hello,
I host a jk2mv server on FreeBSD I've tested it on both 10.3 and 11.1 and it runs fine.  In order to compile though I needed to modify a line in qcommon/q_shared.h because this OS isn't defined in there.  I just used the linux options and there were no issues compiling with clang 4.0.  I did receive 2 warnings which are listed below.

```
$ diff q_shared.h ../../../../245d9da/jk2mv/src/qcommon/q_shared.h
250c250
< #ifdef __linux__
---
> #if defined(__linux__) || defined(__FreeBSD__)
```
These are the build options I used to compile..
```
$ cat freebsd-build-and-install.sh 
type cmake >/dev/null 2>&1 || { echo >&2 "Can't find cmake."; exit 1; }

BUILD_DIR="`uname`-`uname -m`-install"
mkdir "$BUILD_DIR"
cd "$BUILD_DIR"

cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release \
          -DUseInternalPNG=OFF -DUseInternalJPEG=OFF -DUseInternalZLIB=OFF -DUseInternalMiniZip=ON \
          -DCMAKE_EXE_LINKER_FLAGS="-lexecinfo -L/usr/local/lib -ldrm" \
	  -DBuildMVMP=ON -DBuildPortableVersion=OFF ../..

make
sudo make install
```
These are the two warnings I received compiling, not sure if they are specific to this platform..
```
[  6%] Building C object src/menu/CMakeFiles/jk2mvmenu_amd64.dir/ui_shared.c.o
/usr/home/brourke/jk2/245d9da/jk2mv/src/menu/ui_shared.c:6591:15: warning: explicitly assigning value of variable of type 'unsigned int' to itself [-Wself-assign]
                                        uiLetter = uiLetter;    // breakpoint line only
```
```
[ 41%] Building CXX object src/CMakeFiles/jk2mvmp.dir/client/FxScheduler.cpp.o
/usr/home/brourke/jk2/245d9da/jk2mv/src/client/FxScheduler.cpp:1241:12: warning: address of array 'origin' will always evaluate to 'true' [-Wpointer-bool-conversion]
                                                if ( origin )
```

**Comment by ouned** [comment]
Did you also test the client?
What's the deal with the CMAKE_EXE_LINKER_FLAGS?

You can make a pullrequest for the changes.

**Comment by brourke228** [comment]
Actually I'm not sure why I added libdrm in there because I just tried compiling again without and it and worked fine.  That might have been something giving me issues when I compiled on freebsd 10.3.  Without the -lexecinfo flag however I get this linking error...
```
[ 66%] Linking CXX executable ../out/Release/jk2mvmp
CMakeFiles/jk2mvmp.dir/sys/sys_unix.cpp.o: In function `Sys_BacktraceSymbol':
/home/brourke/jk2/245d9da_3/jk2mv/src/sys/sys_unix.cpp:1087: undefined reference to `backtrace_symbols'
/home/brourke/jk2/245d9da_3/jk2mv/src/sys/sys_unix.cpp:1087: undefined reference to `backtrace_symbols'
CMakeFiles/jk2mvmp.dir/sys/sys_unix.cpp.o: In function `Sys_PrintBacktrace()':
/home/brourke/jk2/245d9da_3/jk2mv/src/sys/sys_unix.cpp:750: undefined reference to `backtrace_symbols'
CMakeFiles/jk2mvmp.dir/sys/sys_unix.cpp.o: In function `Sys_BacktraceFrom(void**, int, void**, void*)':
/home/brourke/jk2/245d9da_3/jk2mv/src/sys/sys_unix.cpp:973: undefined reference to `backtrace'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /usr/home/brourke/jk2/245d9da_3/jk2mv/build/FreeBSD-amd64-install
*** Error code 1

Stop.
make[1]: stopped in /usr/home/brourke/jk2/245d9da_3/jk2mv/build/FreeBSD-amd64-install
*** Error code 1

Stop.
make: stopped in /usr/home/brourke/jk2/245d9da_3/jk2mv/build/FreeBSD-amd64-install
```

I wasn't able to test the client because there isn't a display on that machine but it did compile.  I could probably install trueos in vmware on another computer to test it out.

**Comment by aufau** [comment]
Try the branch above (with provided .sh scripts)

**Comment by brourke228** [comment]
I had to edit your build script to run it because freebsd uses /bin/sh as the default shell.  Bash installs to /usr/local/bin/bash if you add the package for it.  With the UseInternalMiniZip disabled I also get the following error compiliing..
```
[ 87%] Building CXX object src/CMakeFiles/jk2mvded.dir/qcommon/files.cpp.o
/usr/home/brourke/jk2/test/jk2mv/src/qcommon/files.cpp:17:10: fatal error: 'minizip/unzip.h' file not found
#include <minizip/unzip.h>

```
I do have the minizip package installed.  The file its looking for is located at /usr/local/include/minizip/unzip.h

If I use the internal minizip it compiles with your changes without any errors.

**Comment by brourke228** [comment]
It works now with your latest branch.  I don't get any compiler errors or warnings and I was able to start jk2mvded without any issues.  Thanks for making those changes.

**Comment by aufau** [comment]
Great. I'll merge it and close the issue then. Thanks for making a pull request too even if it won't be merged in the end. Turned out there was some more cleanup to be done and I did all this in my repo.
