### ISSUE TITLE
Can't save force powers

### ISSUE THREAD

**Issue by Lomtvador** [mvdevs/jk2mv#102]
![shot0004](https://user-images.githubusercontent.com/24492734/40980130-6d7f0f58-68e0-11e8-9050-313040c61992.jpg)
![untitled](https://user-images.githubusercontent.com/24492734/40980140-72964646-68e0-11e8-91b1-647f1e90b127.png)
When I trying to save force, jk2mv creates blank file.
I using jk2mv from latest commit https://github.com/mvdevs/jk2mv/commit/245d9da770aaff3f844cbd425be299dde0c0ab7d

**Comment by ouned** [comment]
works for me.
are you running any mods?

**Comment by Lomtvador** [comment]
No mods in base and in rus1 directory.
![image](https://user-images.githubusercontent.com/24492734/40988947-1c00922c-68f5-11e8-90a4-29c2a8b74e82.png)
![image](https://user-images.githubusercontent.com/24492734/40988963-2596ef5c-68f5-11e8-8ca2-fc95f00730ab.png)

**Comment by ouned** [comment]
still cant reproduce :S
can you test official 1.4.1?

**Comment by Lomtvador** [comment]
I tested 1.4.1 and didn't find that bug.

**Comment by ouned** [comment]
awesome find @Lomtvador

**Comment by Daggolin** [comment]
Should be fixed now.
