### ISSUE TITLE
Leader's score is always zero

### ISSUE THREAD

**Issue by Lomtvador** [mvdevs/jk2mv#103]
Connect to any server and watch leader's score. It's always zero until he kill someone or die.
Here screenshot when I connected to server:
![shot0000](https://user-images.githubusercontent.com/24492734/41196361-d3dcc902-6c46-11e8-9afb-af0e54c61a18.jpg)
Here when bot killed me:
![shot0001](https://user-images.githubusercontent.com/24492734/41196363-dff47b7c-6c46-11e8-93e3-281565fb4705.jpg)
This bug exists in JK2MV 1.4.1 and https://github.com/mvdevs/jk2mv/commit/a10def9ad48e17002ce6d6a2573b96c75e1bafb0
I noticed that bug disappears if I delete assetsmv2.pk3 from base.

**Comment by aufau** [comment]
It will be fixed in jk2mv sometime later when mvsdk patches are merged-in.
