### ISSUE TITLE
Bot's message freeze people

### ISSUE THREAD

**Issue by Lomtvador** [mvdevs/jk2mv#104]
Steps to reproduce:
1. Spawn many Luke bots.
2. Kill him until you see this message:
![shot0000](https://user-images.githubusercontent.com/24492734/41815326-00da5e4a-7770-11e8-9638-d699271963be.jpg)
3. You're stuck.
I suspect that reason is quotation mark. I opened file botfiles\Luke.jkb in assets0.pk3 and found this:
![2](https://user-images.githubusercontent.com/24492734/41815393-40ee959e-7772-11e8-87af-5828d49d6a64.png)
These quotation marks are different:
![1](https://user-images.githubusercontent.com/24492734/41815399-5eec1238-7772-11e8-87b6-7da1768b4420.png)
Original jk2mp prints this message without this quotation mark. Just space instead of mark.
I encountered this in jk2mv 1.4.1. I also believe that I saw this bug before jk2mv 1.4.

**Comment by aufau** [comment]
Fixed, thanks for reporting. It was a serverside issue.
