### ISSUE TITLE
SV_ConnectionlessPacket: IP Rate Limit Exceeded, dropped # requests

### ISSUE THREAD

**Issue by StrikerMan780** [mvdevs/jk2mv#105]
For some reason, everyone will occasionally and randomly get dropped from my servers, and are unable to reconnect for a while, and my server console gets spammed with this:

![Console Spam](https://i.imgur.com/utSSMTd.png)

**Comment by aufau** [comment]
It appears that when this happen, your servers is under a DOS attack. Not sure why the rate limiter doesn't help though. What you can do right now is to enable `/developer 1` and `/logfile 1` to collect more information when an attack happens again. Don't post these extended logs here as they contain sensitive information (IP addresses).

Please contact me on discord: https://discord.gg/KFaeCpR or by some other means, privately to discuss the issue further.

**Comment by aufau** [comment]
There was no additional info for almost a year so I close the issue
