### ISSUE TITLE
remove "following player" text from demo playback

### ISSUE THREAD

**Issue by carmesie** [mvdevs/jk2mv#109]
Hello, im a fellow JK2 player from 1.02 scene, i want to render some clips that were recorded in spectator mode and id love to remove the "following x player" text that is displayed in the next image..in order to render the scene. is there anyway to do this without cg_draw2d? 
![shot0002](https://user-images.githubusercontent.com/43766874/46381520-a0bc4880-c674-11e8-9766-ccab9f021c7a.jpg)

**Comment by aufau** [comment]
You need to either make a mod that disables it, have someone make such mod for you (very easy, relevant code: https://github.com/mvdevs/mvsdk/blob/master/code/cgame/cg_draw.c#L3521-L3538) or maybe use jomme that I believe has cvars for this: https://jkhub.org/files/file/1861-jomme/

JK2MV alone doesn't provide such option.
