### ISSUE TITLE
Optionally load and write all configs to base rather than mod directories

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#111]
com_globalConfig or fs_globalConfig.

**Comment by TriForceX** [comment]
fs_globalConfig

**Comment by Daggolin** [comment]
Going to merge "fs_forcegame" instead, which allows users to specify a folder to override "fs_game" with, which will be used for configs, screenshots etc. So setting "fs_forcegame" to "base" is going to cover this.

Reference: https://github.com/Daggolin/jk2mv/commit/afbbd51a656f0aa1eefbf5812372eecac8a116dc

**Comment by aufau** [comment]
Is this done?

**Comment by Daggolin** [comment]
Rebased the commit from the "forceGame" branch on top of master. So as of d99db29e816a526986efe41769ee56fb3557fad5 the game can be started with `+set fs_forcegame base` for a similar effect. The "fs_game" directory is still loaded, but the "fs_forcegame" directory overrides it. That way custom pk3s downloaded into "fs_game" directories should still work.
