### ISSUE TITLE
Allow using windows accelerated mouse input instead of raw

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#113]
This may require modifying sdl2/compiling it with special flags, or waiting until mainline sdl enables this as an option by default. Or emulating windows accel in jk2mv, but this would require configuration by user.

in_mouse 1 = raw input, in_mouse 2 = windows input

**Comment by Daggolin** [comment]
As far as I can tell this should be implemented as of https://github.com/mvdevs/jk2mv/commit/12fbd0647465f0049fd068dc3295a33014dc9e01.
Closing this for now.
