### ISSUE TITLE
Crash when launching server with http downloads behind NAT

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#118]
Reported by Flate
OS: Arch Linux, Debian

> If you’re setting a server up with http dl enabled and your ip is being behind a nat so the http server can’t find a valid Port do gather the file through the game crashes for me or rather freezes while attempting to download

Needs confirmation

**Comment by Daggolin** [comment]
Does the freeze occur on the server or the client? If it's an issue on the client-end it might be related to the deadlock described in #91 when removing the http server.
