### ISSUE TITLE
Merge jk2mv's menu code into mvsdk's ui code and general ui/menu improvements

### ISSUE THREAD

**Issue by Daggolin** [mvdevs/jk2mv#119]
As the title suggests the mvmenu code in the jk2mv repository and the ui code in the mvsdk repository are both based on the jk2 ui code. So instead of maintaining two separate versions of almost the same module code it would be best to merge the mvmenu into the ui code to build both from a shared codebase (mvsdk is a submodule of jk2mv already). When merging both ui codebases various other fixes, improvements and changes to the ui could be made.

Mostly done and ready to be reviewed and merged:
https://github.com/Daggolin/jk2mv/commits/mvmenu-ui-merge
https://github.com/Daggolin/mvsdk/commits/mvmenu-ui-merge

**Comment by TriForceX** [comment]
Looks fine for me, except 3 things:
- The JK2 3D logos at the main menu are streched
- The JK2 logo at the top is streched
- The JK2 loading screen while connecting is streched

**Comment by ouned** [comment]
close?

**Comment by Daggolin** [comment]
Merged since ec783dc6d233dda3610ab5eafd50b9ba699420b8.
Closing this.
