### ISSUE TITLE
Wrong server refresh data

### ISSUE THREAD

**Issue by TriForceX** [mvdevs/jk2mv#137]
In favorites source when you get a new list or refresh the list the players count goes wrong.

In the example there are 11, but when get a new list the value multiply x 2, and when i refresh it the value goes random (319, 132, 143, etc...)

![imagen](https://user-images.githubusercontent.com/16083854/82708577-946f6f80-9c4c-11ea-913d-36385fc1db5e.png)

![imagen](https://user-images.githubusercontent.com/16083854/82708591-a18c5e80-9c4c-11ea-9c99-42b86990340a.png)

**Comment by Daggolin** [comment]
Fixed on mvdevs/mvsdk@86365b51f94d95638f8aabd4290c43a5c9469447.
