### ISSUE TITLE
Add syscall writing to the console without any notification

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#144]
It was requested for cgame chat (like in jka). Check if Bucky's eternaljk doesn't have something similar already.

Effort: Small
Difficulty: Medium

**Comment by Daggolin** [comment]
Solved by https://github.com/mvdevs/jk2mv/commit/13c6a8a7b18d78f45f561f5dfd32621b69fdb969 and https://github.com/mvdevs/jk2mv/commit/8f880996db632ce32e877ef4ce984ae5a2f92c0d.
