### ISSUE TITLE
back port dynamic glow from JA 

### ISSUE THREAD

**Issue by WhiteMagicRaven** [mvdevs/jk2mv#156]
Hello, if that possible please back port from Jedi Academy a DynamicGlow (bloom effect)
to Jedi Outcast
its effect comes from all glowing sources , like lamps, etc ... 
looks really nice )
Thanks for your great source port) 
That all)

**Comment by TriForceX** [comment]
Is already implemented.

r_dynamicGlow 1/0 Enable / Disable dynamic glow effect.
r_saberGlow 1/0 Enable / Disable dynamic glow on saber shaders. Turn off if it breaks your custom saber model.

Just JK2 stuff doesnt make usage of it, so you have to add it manually.

For example adding the "glow" parameter like JKA will enable the effect on the desired shader, this is an example of a JKA map running in JK2.

Before:
![image](https://user-images.githubusercontent.com/16083854/211823816-15be74fe-edb6-4c42-95c7-d9c018dcf189.png)

After:
![image](https://user-images.githubusercontent.com/16083854/211824511-ff4405e9-e3eb-441d-b556-bda71a2f72db.png)

For more customization & recommended usage:
https://github.com/mvdevs/jk2mv/wiki/Dynamic-Glow-Shaders
