### ISSUE TITLE
Can't build on Ubuntu arm64

### ISSUE THREAD

**Issue by ArtemS2** [mvdevs/jk2mv#167]
[  1%] Building C object src/mvsdk/tools/asm/CMakeFiles/q3asm.dir/q3asm.c.o
In file included from /home/artem/builds/jk2mv/src/mvsdk/tools/asm/q3asm.c:23:
/home/artem/builds/jk2mv/src/mvsdk/tools/asm/../qcommon/q_platform.h:198:28: error: missing binary operator before token "or"
  198 | #elif defined(aarch64) or defined(ARCH_ARM64)
      |                            ^~
/home/artem/builds/jk2mv/src/mvsdk/tools/asm/../qcommon/q_platform.h:325:2: error: #error "Architecture not supported"
  325 | #error "Architecture not supported"
      |  ^~~~~
/home/artem/builds/jk2mv/src/mvsdk/tools/asm/q3asm.c: In function ‘InitTables’:
/home/artem/builds/jk2mv/src/mvsdk/tools/asm/q3asm.c:1302:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
 1302 |         for ( i = 0 ; i < NUM_SOURCE_OPS ; i++ ) {
      |                         ^
make[2]: *** [src/mvsdk/tools/asm/CMakeFiles/q3asm.dir/build.make:90: src/mvsdk/tools/asm/CMakeFiles/q3asm.dir/q3asm.c.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:523: src/mvsdk/tools/asm/CMakeFiles/q3asm.dir/all] Ошибка 2
make: *** [Makefile:156: all] Ошибка 2

**Comment by aufau** [comment]
Hi, please try with this new patch. It should compile now.
