### ISSUE TITLE
macosx, linux minimizer

### ISSUE THREAD

**Issue by ouned** [mvdevs/jk2mv#22]
in the moment the minimizer is only implemented for windows

**Comment by vvvjk2** [comment]
I suggest also making the minimize bind work for right Windows button and not only left, since some keyboards (like my own steelseries) don't have a left Win button. Enabling alt-tabbing is a nice solution as well, in my opinion.

**Comment by ouned** [comment]
good idea
for macosx we need another key nonetheless
