### ISSUE TITLE
Error messages spamming console

### ISSUE THREAD

**Issue by comeroof** [mvdevs/jk2mv#3]
Version: JK2MV b3 / 1.02
I noticed following error / warning messages spamming the console:
- "Sys_QueEvent: overflow (event type 3)"

And when playing on specific servers (not every server):
- "WARNING: refusing to create relative path ..."
- "Couldn't write ..."

**Comment by ouned** [comment]
on which os are you?

**Comment by comeroof** [comment]
Linux

**Comment by ouned** [comment]
i guess it's a case sensitive problem then, windows doesn't care, linux does.

**Comment by ouned** [comment]
Couldn't reproduce this one at all... please provide more information. (distro? self-compiled? the path?)
make sure jk2mv has write access to ~/jk2mv

**Comment by comeroof** [comment]
The actual warning message reads like this (it only happens on ownage city server 1.02):

"WARNING: refusing to create relative path /home/myuser/jk2mv/...base/jk2mvconfig.cfg"

Maybe I have to add that I created symlinks to all mods folders in /home/myuser/jk2mv/ to one single folder there, so everything is written to one single file. But I can't imagine why it won't work, since this message shows only on one single server.

The "Sys_QueEvent: overflow (event type 3)" message happens when I play for a while and press TAB for the scores. I think it has something to do with updating the configstrings/player infos.

**Comment by ouned** [comment]
Please test it without your symlink modifications on the server you have problems.
"/home/myuser/jk2mv/...base/jk2mvconfig.cfg" is no valid path

**Comment by comeroof** [comment]
Tested it. Same issue. Could it be that the server mod tries to make that strange "...base" dir?

**Comment by ouned** [comment]
Yeah could be what's the servers name? 

Am 1. April 2015 16:07:36 MESZ, schrieb comeroof <notifications@github.com>:
>Tested it. Same issue. Could it be that the server mod tries to make
>that strange "...base" dir?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mvdevs/jk2mv/issues/3#issuecomment-88497615

--
Michael Losert <michael@losert.org>
https://ouned.de

**Comment by comeroof** [comment]
"Ownage City"

**Comment by ouned** [comment]
found the bug. it's the servers fault. happens on windows, too.

**Comment by comeroof** [comment]
Haha, can u elaborate what the problem was? Thx! :)

**Comment by ouned** [comment]
well the fs_game directory name contained some strange char which came from reading a utf-8 file and interpreting it as a ascii file

**Comment by vvvjk2** [comment]
The "Sys_QueEvent: overflow (event type 3)" spam still happens a lot for me, on UNIX.
I suggest changing the Com_Printf call to Com_DPrintf.
