### ISSUE TITLE
Updated menus

### ISSUE THREAD

**Issue by Daggolin** [mvdevs/jk2mv#34]
Menu patchfiles should be updated to show the client cvars in the menu.

- [x] download popup
- [x] download blacklist file removal list
- [x] cvars (?)
- [x] recording options (for easy access of @entdark's work)
- [x] move dynamic glow setting to graphic settings in ingame menu

**Comment by TriForceX** [comment]
client cvars are already added on ingame jk2mv controls (pull request #51). 
so, we should add the server cvars into server creation menu? (advanced options)

**Comment by ouned** [comment]
updated

**Comment by aufau** [comment]
- [x] Anisotropic filtering levels (in old `More Video -> Anisotropic Filter` field)

Do we want to add more gfx cvars? Maybe have new presets using them?

**Comment by TriForceX** [comment]
@aufau i think yes, also with font cvars maybe

**Comment by aufau** [comment]
Ok, what new cvars I'd like to see in the menu:

- r_consoleFont
- r_dynamicGlow
- r_ext_multisample (if it actually works)
- r_gammamethod
- cl_autoDemo
- mv_consoleShiftRequirement

Extras:
- con_height
- con_scale
- con_timestamps
- mv_nameShadows
- r_fontSharpness
- cl_drawRecording

And new menu video quality presets.

I think we should omit cvars that are enabled by default and "just work" like r_fontSharpness

**Comment by aufau** [comment]
Closed by c4dcc9b806151a90c948226b57fa5bc1753d1ef3
