### ISSUE TITLE
Serverlist not updating correctly

### ISSUE THREAD

**Issue by comeroof** [mvdevs/jk2mv#4]
I'm not 100% sure about this one, but sometimes when I update the serverlist some servers aren't shown at all. I know that these servers reporting to all the master servers of ouned, jk2master.ravensoft and jkhub.
When I add these servers to the favourites list, they aren't updated correctly and cannot be joined although they work perfectly fine with original JK2.

For example the server: 46.38.237.114:28070 "-BT3-". (1.02, it runs NT mod)

**Comment by ouned** [comment]
Neither me nor Daggolin could reproduce that. :/

**Comment by comeroof** [comment]
Alright, I think we can close this issue then. Has to be an error on my end although it's very confusing why this happens ^-^.
