### ISSUE TITLE
Multiversion QVMs

### ISSUE THREAD

**Issue by ouned** [mvdevs/jk2mv#41]
@Daggolin is working on Multiversion QVMs which will be part of the mvsdk he is working on.
JK2MV 1.2 will ship with bugfixed, improved but still mostly basejk versions of them.

**Comment by ouned** [comment]
moving this to 1.3, too much work and we already have enough in the pipeline for 1.2

**Comment by AlexCSilva** [comment]
Does this work yet?

**Comment by Daggolin** [comment]
Not fully. I am fixing some things, but it's almost ready now. My bad that it got delayed that long.

**Comment by AlexCSilva** [comment]
Amazing work :) 👍

**Comment by ouned** [comment]
done.
