### ISSUE TITLE
Sane homePath on linux

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#43]
Setting default "homePath" to `$HOME/jk2mv` is wrong. It should be classic `$HOME/.jkii` or `$HOME/.jk2mv`. I'd use first one, as there is no "official" jk2 client for linux and resource files are all compatible afaik.
Modern approach would be using [XDG specs] (http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) but it's not worth it in this case.

**Comment by ouned** [comment]
okey, but why is it wrong?
I'd go with ``$HOME/.jk2mv`` because we have separate names on osx and windows, too.

**Comment by aufau** [comment]
Basically for linux user it's like putting it on your desktop on windows. There was no standard, but putting user-owned files in `$HOME/.$SOFTWARENAME/` is an unwritten rule. Files and directories starting with dot are "hidden".
There is a proper standard now (mentioned earlier) but it looks like there is a 50-50 split currently. It's definitely ok to still use the old rule.

**Comment by ouned** [comment]
okey, so it's going to be ``.jk2mv``
thanks
