### ISSUE TITLE
Use SDL across all platforms ala OpenJK

### ISSUE THREAD

**Issue by ensiform** [mvdevs/jk2mv#44]
Plans to move to SDL2 across all platforms in the future like we did with OpenJK?

**Comment by ouned** [comment]
I like the idea using SDL on windows, too but it fells rather incomplete.
The SDL code still misses a dedicated server console (when creating one from the menu)
Maybe I'm going to address that. It could work to just open "cmd.exe jk2mvmp.exe +set com_dedicated 2" I guess? (only on win32 ofc)

**Comment by ensiform** [comment]
That would be silly.  My code uses fullscreen console but that is not available yet.

**Comment by ouned** [comment]
There is also the problem with compatibility across different versions of visual studio and precompiled import lib / dll. I also don't really like precompiled stuff somehow.
We are already doing this for softoal though. :/

**Comment by ensiform** [comment]
We haven't even gotten to replacing the AL code yet. The entire sound backend is an utter mess compared to Q3.

**Comment by ensiform** [comment]
Here's what dedicated looks like currently in my OJK locally (non-ded executable)
Also has new cvar and cmd stuff WIP too

![image](https://cloud.githubusercontent.com/assets/997399/10154102/e22fa9a6-6628-11e5-90b0-aa703316dde4.png)
