### ISSUE TITLE
[regression] Ctrl-v doesn't work anymore

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#47]
Commit 8084729 introduced a regression, ctrl-v and few other shortcuts in Field_CharEvent don't work anymore. On the other hand, Issue #7 it was supposed to fix doesn't happen when I remove converting chars to uppercase code on current HEAD (can't simply revert because it was overwritten). 

Tbh I can't see where is there a requirement for upper-case characters in ui code or why it would work on windows.

**Comment by ouned** [comment]
#7 only appears if you try to bind a key in the menu which was already bound to something else.

so reverting 8084729e982622bb8291868f7978e2a2150671dc is no option.

Windows still has it's plain old win32 code which makes no use of SDL.

**Comment by aufau** [comment]
Again, can't reproduce #7 when I removed "converting to uppercase code" from current master.
Maybe I'm gonna have a second look after, thought you could explain why this patch was needed exactly.

**Comment by ouned** [comment]
``#7 only appears if you try to bind a key in the menu which was already bound to something else.``
that's supposed to be an extended explanation :D

**Comment by ouned** [comment]
Ok, so I may have found a solution for it.
The problem seems to be that only SE_KEY is expected to be uppercase.

@aufau can you please test the following patch: http://slexy.org/raw/s217dvr9Mb before I push it?

btw. another aspect of #7 is that it looks like it works but when trying to use the bind it doesn't work. If you close the menu and reopen it you will see that it actually binded nothing. I even tested that again to be sure.

**Comment by aufau** [comment]
Ok, I had a second look at the issue. The underlying problem is that client always stores binding to the uppercase character (Key_SetBinding), and reads from requested char, no matter if it's upper or lower case (Key_GetBinding). UI code on the other hand doesn't put equivalence between upper and lower characters. Therefore bindings from config and /bind command are uppercase and bindings from menu are lowercase in the UI code (g_bindings table). Further bugs emerge from this.

Typing it here just for the reference.

Your solution looks OK and works for me.

**Comment by ouned** [comment]
It could be fixed in the menu code but mods would then cause problems on unix and not on windows. Thats something we try to avoid^^
