### ISSUE TITLE
change the name for "mv_nameShadow"

### ISSUE THREAD

**Issue by TriForceX** [mvdevs/jk2mv#52]
I think this cvar need to be changed to something like "mv_coloredShadow", because the "nick name" is not the only thing affected by an colored shadow, all of strings texts marked as ITEM_TEXTSTYLE_SHADOWED can have a "colored shadow"... anyways, is an suggestion :smile:

**Comment by ouned** [comment]
@Daggolin

**Comment by Daggolin** [comment]
Sounds like a good idea, but it might confuse a few players who used the old cvar if the colored shadows reverted back to default settings.

**Comment by TriForceX** [comment]
well, maybe in the next release we can note it in the changelog, this cvar is now on the jk2mv ingame setup, we can note that too. 

few people know the existence of this command ( normal people ) , but those who know the cvar will detect if that option changed, they immediately will seek in where to change.

if you change it, i will have to change the translations i recently did, so keep me notified. :smiley:

**Comment by ouned** [comment]
i'd be for renaming it, too

**Comment by Daggolin** [comment]
Changed.
@TriForceX can you check the translations, please?

**Comment by TriForceX** [comment]
@Daggolin ok im checking
