### ISSUE TITLE
Improve bots filter check

### ISSUE THREAD

**Issue by TriForceX** [mvdevs/jk2mv#53]
I suggest to change this:

https://github.com/mvdevs/jk2mv/blob/b25d7478ab1183e42222029614650486ca4b7016/src/client/cl_main.cpp#L3532

because local players also can have ping 0, the current "ping == 0" filter is interpreting real players with ping 0 as bots in the server list, i suggest to change it for something like the remoteAddress.type == NA_BOT, so u need to parse a client info for that i think... or checking if the client has the "skill" field in his info (that is only from bots) but i think is unsafe. idk what is better :yum:

**Comment by ouned** [comment]
You dont get that information from the server. Thats why it is turned off by default.

**Comment by TriForceX** [comment]
so? it will stay that way? interpreting real players with ping 0 as bots? :disappointed:

**Comment by Daggolin** [comment]
We can't change that, as we don't have the IPs of clients. Ping is the only thing we can use, but as you said, if you are hosting a server on the same pc you are playing from, you are probably going to be filtered as if you were a bot.
