### ISSUE TITLE
Can't input colorcodes on unix

### ISSUE THREAD

**Issue by ouned** [mvdevs/jk2mv#6]
Typing e.g. ^2 to create a green text doesn't work on unix platforms, it creates what it actually should "²"

This needs a workaround.

**Comment by comeroof** [comment]
I can use the color codes without problems. Also in the player menu and ingame (chat). Linux x64 here, can't speak for Mac.

**Comment by ouned** [comment]
:o which keyboard layout are you using?

**Comment by comeroof** [comment]
Dvorak.

Nah kidding. I'm using qwertz (German keyboard).

**Comment by ouned** [comment]
i was wrong with this one.. it works
thing is that if using a keyboard with deadkeys enabled you need to press "^" two times to get a "^"
this seems to be perfectly normal and also works in jk2mv
