### ISSUE TITLE
Add unique ID to mv.sp

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#60]
Leaving it without one makes it default to 0. This confuses noob modders like myself who register their own strip files without ID and they overwrite each other in stri.cpp:SP_ListByID.

I'd suggest setting it to something other than 0, as this may break some legacy mods who got it wrong too.

**Comment by ouned** [comment]
hmmm, I expected to avoid that by manually loading it :/
Why is that not enough?

**Comment by aufau** [comment]
I thought I explained it already: ``cStringPackageSingle.ID`` gets initialized to 0 and set to ID token value on ``cStringPackageSingle::Load``. On the other hand in SP_Register you've got ``SP_ListByID[new_sp->GetID()] = new_sp`` so if ID is not unique, it will overwrite. This double association (by file name and by predefined id) is rather dumb, but we can't change it.

What you achieved by loading it in menu/ code is that mv.sp will be available even with ui mods… unless they overwrite it by their own .sp file with ID 0.
