### ISSUE TITLE
Several missing out of bounds checks in the ui module

### ISSUE THREAD

**Issue by ouned** [mvdevs/jk2mv#61]
e.g. when setting g_maxForceRank to something > 7 it reads from unallocated memory locations and thus crashes the game in some cases.

@aufau already made some fixes for that
https://github.com/aufau/jk2sdk-gpl/commit/a1618762b1b1bb375ce7396dceecc15199a22c29

**Comment by aufau** [comment]
Is this still an issue? Compilers and [Clang Static Code Analyzer](http://jk2world.net/files/jk2mv/clang-analyzer/scan-build-2016-05-18-013126-8301-1/) indicate no such problems anymore and they are pretty good at finding them. g_maxForceRank issue was fixed in  2511513.

**Comment by ouned** [comment]
im not aware of anything else. @Daggolin ?

**Comment by Daggolin** [comment]
I am not aware of anything else either.
