### ISSUE TITLE
Raw Mouse Input

### ISSUE THREAD

**Issue by Daggolin** [mvdevs/jk2mv#64]
Every now and then people ask about raw mouse input and some players who got issues with their mouse on jk2mp, jamp, etc. say that they don't have issues on OpenJK when they use raw mouse input.

Maybe we should add support for raw mouse input, too?

OpenJK references:
https://github.com/JACoders/OpenJK/issues/202
https://github.com/JACoders/OpenJK/pull/215

**Comment by TriForceX** [comment]
+1 for this :+1: ive tried some mods with this feature, the experience is much better

**Comment by Razish** [comment]
FWIW OpenJK now uses SDL2 which has this by default.

**Comment by Daggolin** [comment]
Ah, thanks for the info, but we're still not using SDL2 on Windows.
