### ISSUE TITLE
Add console font before 1.2 release.

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#69]
Code New Roman is ready and can be downloaded from there: https://jk2.info/viewtopic.php?f=34&p=4000#p4000

I'm haven't added it yet to avoid trashing repository in case somethings changes. I think this is a good practice. Maybe we should keep these binary files in a separate repo until release or keep them as _git submodule_? The problem is that git hasn't been made for binary blobs and each update permanently increases repository size without any delta compression.

**Comment by TriForceX** [comment]
why not another branch with the all font things resources? so if u do changes there, will be easy to merge to another branches

**Comment by ouned** [comment]
@TriForceX what fau means is the size of the whole repo so cloning it takes longer because of the binary files. (deleting them afterwards doesnt help because you always clone the whole thing)

**Comment by aufau** [comment]
Patches are in the repo and improved fonts are floating around, I don't expect any further changes. It's just the matter of adding them to repo right before the release now.

**Comment by aufau** [comment]
Closed by 622424c9240eef372413371f3537e27720ff7669 and 357e60e31e03069bbe0468b236bc9e2d855ee4a2
