### ISSUE TITLE
Debug symbols / better crash handling

### ISSUE THREAD

**Issue by ouned** [mvdevs/jk2mv#77]
Include debug symbols for all builds.
For auto-generating backtraces, etc.

Ideally, automatically save crashdumps to a file which can be uploaded to the forums.

**Comment by aufau** [comment]
For unix, branch crashlog I merged does all this and more: https://github.com/mvdevs/jk2mv/commit/093ac14cc67cf5705707b4d65682528ab2ad783e

The remaining "controversy" if we should also append cvar values (think of mod passwords etc.)
Another thing is that there is a possibility of automatically sending these crashlog back to us.

**Comment by ouned** [comment]
this has been done for all platforms now.
