### ISSUE TITLE
Movement around forcefields is choppy

### ISSUE THREAD

**Issue by syrobee** [mvdevs/jk2mv#78]
Video: https://www.youtube.com/watch?v=3zhY3K9v50E
The recording software I used doesn't capture the frames very well, but I hope you can see the movement that I'm talking about.

**Comment by ouned** [comment]
Thats a feature! :P
Cant be fixed in jk2mv, its part of the game/cgame module
Should be fixed there

**Comment by Razish** [comment]
IIRC fixing this breaks netcode compatibility (something about non-uniform AABBs)
JKG had it fixed (for reference)
