### ISSUE TITLE
CMake: Fix assets target

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#79]
Assets target doesn't update assets.pk3 when source files are modified.

**Comment by aufau** [comment]
So thanks to ouned's efforts assets target ``assets/assetsmv.pk3`` updates correctly, but the pk3 still doesn't get copied to ``out/base/assetsmv.pk3``

**Comment by ouned** [comment]
it is but only on modifying some source file that is part of jk2mvmp
i couldn't find a solution for this

**Comment by ouned** [comment]
this should work since the integration of mvsdk.
