### ISSUE TITLE
JK2MV 1.2 on OSX Yosemite

### ISSUE THREAD

**Issue by TriForceX** [mvdevs/jk2mv#81]
im currently using JK2MV on OSX Capitan, but i have two friends on OSX Yosemite and theyre having This error: http://i.imgur.com/Jwb35Oa.jpg 

what could be wrong?

**Comment by ouned** [comment]
lol, thanks for reporting before 1.2.1
We may need a newer osx version for 1.2 but it shouldnt be 10.11.. i expected something like 10.8

**Comment by TriForceX** [comment]
oh i see, ok ok.

PD: i have been offline 5 months 🎅  nice to see u all again

**Comment by Daggolin** [comment]
I tried JK2MV 1.2 on 10.9.2, starting it through the terminal (instead of clicking the app icon) and it worked fine. Maybe your friends can use that as workaround for now?

**Comment by ouned** [comment]
can easily be solved:
`export MACOSX_DEPLOYMENT_TARGET=10.9`
or explicitly setting CMAKE_OSX_DEPLOYMENT_TARGET.
