### ISSUE TITLE
Key input in the console

### ISSUE THREAD

**Issue by firestar300** [mvdevs/jk2mv#82]
Hi,

I create this issue because i have a bug. When I open my console, and i press the first key to type something, it doesn't display on the console and i have to repress the key.

I'm on version 1.2.1 and Windows 10.

**Comment by aufau** [comment]
Thanks for reporting. Can you attach config you're using when this happens (type ``/writeconfig issue82.cfg`` in the console)?

**Comment by firestar300** [comment]
[issue82.zip](https://github.com/mvdevs/jk2mv/files/504965/issue82.zip)

**Comment by aufau** [comment]
and issue82_global.cfg pls (forgot about that).

**Comment by firestar300** [comment]
Ok thank you. Mayber it's a conflict with a pk3 file ?
[issue82.zip](https://github.com/mvdevs/jk2mv/files/505201/issue82.zip)

**Comment by ouned** [comment]
this could be a problem with dead keys (because "^" is one)
sometimes i had the same issue but ignored

@aufau can you check whether it happens when you use a keyboard layout with activated dead keys (if you dont already have one like that ofc.)? for the german keyboards there are often two layouts one with and one without dead keys

**Comment by aufau** [comment]
Hmm I've never used/known about dead keys, but it appears that all layouts on linux have some dead keys (eg. alt gr + [ for ö) and I've never had any problems.

**Comment by firestar300** [comment]
An example, on the main menu when I type "quit", I have to press the "Q" key twice.

**Comment by aufau** [comment]
hmm maybe your keyboard has `\`` as a dead key? or `shift + \``? Try setting mv_consoleShiftRequirement to 0 and press only `\`` to open console (without shift). Does it still happen? What's your keyboard layout? (language + os)

**Comment by firestar300** [comment]
Azerty keyboard and Windows 10. I'll try next time.

**Comment by aufau** [comment]
French Azerty?

**Comment by firestar300** [comment]
Indeed.

**Comment by ouned** [comment]
![500px-belgian_keyboard_layout](https://cloud.githubusercontent.com/assets/9250728/26426633/debdfcd6-40d9-11e7-8e6f-714b14e8635f.png)
this one? what happens when you press the key over tab a single time in a text editor?
(dead key means the first press does nothing, only the second does)

**Comment by aufau** [comment]
And what happens when you change keyboard layout in your OS to something that doesn't have dead keys, say US qwerty.

**Comment by firestar300** [comment]
Ok but it works fine on my jk2 crack while it doesn't on jk2mv with the Azerty keyboard.

I finally tried with Qwerty layout and it works as expected. I pressed `/` just once after pressing Shift + ².

**Comment by ouned** [comment]
confirmed for french keyboard layout on windows.
I just set the layout to french.

**Comment by ouned** [comment]
ok so I hopefully fixed this issue
Please download latest build from here: https://jk2mv.org/builds/ to test it

**Comment by firestar300** [comment]
Hi ! Thanks for the latest build but I have a problem. I can't update JK2MV because I have this error : http://imgur.com/sZXodpT

I have a Steam version of JK2 and btw I already used JK2MV.

**Comment by ouned** [comment]
do you still have steam jk2 installed? (you need to)
try running it over steam and then retry installing the build.

did you use the installer last time?

**Comment by firestar300** [comment]
Ok I successfully updated JK2MV (v1.3.1) but the bug is still here. Whatever the key I pressed, I need to press twice.

**Comment by ouned** [comment]
1.3.1 doesnt have the patch you need this: https://jk2mv.org/builds/jk2mv-v1.3-70-g9455265-win32-x86-installer.exe

**Comment by firestar300** [comment]
Nice ! It works ! Good job :)
