### ISSUE TITLE
Cannot compile on linux, keep getting no ZIP executable found error

### ISSUE THREAD

**Issue by AlexCSilva** [mvdevs/jk2mv#83]
Error I keep getting:

CMake Error at src/CMakeLists.txt:258 (message):
   No ZIP executable found! Install 7zip, WinZIP or WinRAR.

even when i try download a zip executable or enable the one that it comes with.

**Comment by ouned** [comment]
it's required to package the assets target. Which distribution are you using? As far as I can remember Ubuntu/Fedora came with `zip` preinstalled.

ubuntu: `sudo apt install zip`
fedora: `sudo dnf install zip`

**Comment by AlexCSilva** [comment]
ubuntu

**Comment by AlexCSilva** [comment]
ah, thanks. that seems to work, thought i tried it before though lol
