### ISSUE TITLE
.surf files ignored for some reason in 1.02.

### ISSUE THREAD

**Issue by StrikerMan780** [mvdevs/jk2mv#87]
Skins in Jedi Outcast can use .surf files to allow one to set up various attributes for surfaces for alternate skins, allowing one to turn on or off various parts, etc.

http://www.mediafire.com/file/z7tahrxzwjxo6ne/link.pk3

This skin has several variants, one with a shield, one without, another with no shield or sheath, etc... Works perfectly fine in Jedi Outcast's EXE. Not in JK2MV, it seems to be ignored there.

EDIT: Seems to affect 1.02 mode specifically.

**Comment by TriForceX** [comment]
mmm looks fine to me, i already tested and all works via console, only 3 icons appear in the player select screen, i think thats the only problem.

also ive created a new surf file to try it and it works: http://prntscr.com/ed28hh

**Comment by StrikerMan780** [comment]
Try in 1.02 mode.

**Comment by Daggolin** [comment]
The handling of .surf files is done by the "cgame" module and 1.02 did NOT support .surf files. As JK2MV is an engine mod your game still loads a 1.02 cgame module when playing 1.02 mode.

To get .surf support in 1.02 mode you should look for a 1.02 cgame modification that brings .surf support to 1.02.

I've seen a couple of them around 1.02 in the last few years, but I don't know what clientsides support .surf and which don't. Someone over at https://jk2.info might be able to help you out with that.

Anyway, thanks for the report, but it's not a bug. ;)

**Comment by Daggolin** [comment]
As of JK2MV 1.4 releases contain updated game, cgame and ui modules (https://github.com/mvdevs/mvsdk). Without installing another cgame mod .surf files should work when playing 1.02 on JK2MV 1.4 or later.
