### ISSUE TITLE
Mod Controls menu like Mod Options

### ISSUE THREAD

**Issue by StrikerMan780** [mvdevs/jk2mv#88]
I'd like to see a "Mod Controls" menu, like "Mod Options" so mods don't have to alter the controls.menu and ingame_controls.menu files.

**Comment by aufau** [comment]
JK2MV doesn't alter ingame "controls" menu. You can simply change it in your mod and it won't collide with anything JK2MV-related. That was not the case with "setup" menu where JK2MV adds some video options and hence "Mod Options".

You can see what menus are altered by JK2MV in this repo's assets/ui directory. You can still override menus patched by JK2MV, but then JK2MV changes will be lost.

**Comment by StrikerMan780** [comment]
The reason I mentioned this, was because I noticed something kind of strange: If you go to the "Mod options" menu, then click controls, you get two menus overlapping one another and thought it may have had something to do with altering the controls menu, but perhaps I'm wrong.

**Comment by aufau** [comment]
Yes, I've known about this for some time. Unfortunately I didn't notice it when I implemented this "Mod Options" menu. I've tried to fix it once by editing menu files, but to no avail. I'm going to close this issue as invalid (no need to introduce "mod controls" menu for know) and we can continue discussion here: https://github.com/mvdevs/jk2mv/issues/89
