### ISSUE TITLE
DynamicGlow is slow on MacOSX

### ISSUE THREAD

**Issue by ouned** [mvdevs/jk2mv#9]
On MacOSX FPS drops down to 20~30FPS when r_dynamicglow is enabled.
I guess that's because of some missing opengl extension, or we are using an extension which is software implemented on osx.

**Comment by ouned** [comment]
removing this from 1.1 milestone because no one of us has a real mac.

**Comment by TriForceX** [comment]
this is only an OSX problem? the same happen to me in ubuntu linux 15.10

**Comment by Razish** [comment]
@redsaurus may have some information on this

**Comment by ouned** [comment]
@TriForceX Maybe. I tested on multiple linux machines (tried to trigger the osx bug on linux because I only have access to a Mac at university ^^) and never got it to "work".
It may look like it for you because the open source drivers on linux are pretty slow compared to the proprietary ones from my experience.

**Comment by TriForceX** [comment]
@ouned oh i see, maybe i can try another drivers to solve the issue? (i think im using custom one's) anyways, is not a BIG problem, i can live without dynamic glow.

About MacOSX, i doesnt have problem, i tested jk2mv in osx-mavericks with an amd card and i had no problems with dynamic glow, no low fps, maybe is an issue with intelHD or nvidia cards?

**Comment by ouned** [comment]
hmm could be possible. If I remember correctly, all of the tested machines had an nvidia card.

**Comment by ouned** [comment]
this could be fixed since 59313f7414a1b36711f04c54e4fdebcca51e1400
is there someone who has a working mac?

**Comment by TriForceX** [comment]
@ouned i have a working mac with jk2, but the last time i tried everything work fine (imac with amd card), i will try on my macbook with intel card. 

anyone tried this in ubuntu? the last time i tried was too slow, nowadays i dont have that OS

**Comment by ouned** [comment]
thanks @TriForceX 
please test on of the more recent builds https://jk2mv.org/builds/

**Comment by TriForceX** [comment]
@ouned  Already tested recent builds on OSX with an AMD video card, everything fine :+1: 

may i try with an intel HD card too?

**Comment by ouned** [comment]
Sure. Looks like it isn't a general problem then or was fixed by something else.
Maybe you can compare e.g. 1.0 vs current git builds on the same machine?

**Comment by ouned** [comment]
Just had the chance to test on a real Mac.
Doesn't seem to be a general problem, it worked just like on windows or linux.
Closing this for now then
