### ISSUE TITLE
Some HTTP downloads fail as 404 even though they exist.

### ISSUE THREAD

**Issue by StrikerMan780** [mvdevs/jk2mv#90]
Whenever I host a server with JK2MV, there's always a few specific files it tries to download, but can't because it says 404, even though the file exists on the server and there's no reason for it to fail.

For example, if I host this: http://mrwonko.de/jk3files/Jedi%20Outcast/Maps/Multiple%20Gamemodes/23790/

It will always 404 on trying to download Hyrule_Town.pk3 on clients who join my server.

I notice any of the files that have difficulty downloading don't have a "Date Modified" date... dunno if that has any relevance. Ones with a Date Modified date work fine.

EDIT: Yep, if I edit the file in a program to give it a Date Modified date, it'll download.

**Comment by ouned** [comment]
weird
the file you linked looks perfectly fine (filename has no special chars etc.)
date modified should not have any impact at all as it is just OS metadata, jk2mv doesnt even read it.

Which OS are you on?
Can you somehow show your servers file hierarchy? (maybe it's a path length problem or something similar)

**Comment by StrikerMan780** [comment]
It's not a path length problem. It's related to the Date Modified value.

The folder is just D:\Games\JK2MV\ShadowMavrks\*.pk3

**Comment by ouned** [comment]
how do you know it doesn't have a last modified timestamp?
i just checked and all my files have one, even if its just the same as creation date.
Which filesystem are you using on D:\ ?
Windows version?

**Comment by StrikerMan780** [comment]
NTFS, Windows 10. I know it didn't have a last modified timestamp because it was completely blank. Didn't have one in details or properties.

**Comment by ouned** [comment]
sry for late reply
i think you should check your filesystem

try to do the exact same on another HDD

**Comment by StrikerMan780** [comment]
Makes no difference, Filesystem is undamaged.

**Comment by ouned** [comment]
I tried to reprocedure it but wasn't able to.
Do you have any other unusual changes in your jk2mv installation?
Try doing the same with some minimalist server config (only jk2mvded and base/assets[0,1,2,5].pk3)

**Comment by StrikerMan780** [comment]
No unusual changes. Also, it's just a base install of JK2MV with +fs_game set to another folder for my mods. Also, this is a listen server.

**Comment by ouned** [comment]
closing this for now
