### ISSUE TITLE
Client deadlock when trying to download a file from server with HTTP downloads disabled

### ISSUE THREAD

**Issue by aufau** [mvdevs/jk2mv#91]
Steps to reproduce:

1. Run a dedicated server with mv_httpdownloads 1 and some downloadable assets.
2. Connect with a client missing these assets and deny downloading them.
3. Switch mv_httpdownloads to 0 and restart map on the server.
4. On client pop-up appears (it shouldn't). When you click "Yes".

Then client goes into a deadlock waiting for `m_cldls` mutex in `NET_HTTP_DownloadProcessEvents` in the main execution thread (there is no http server thread anymore).

Also consider if it's possible to apply mv_httpdownloads cvar value on `net_restart` command.

**Comment by ouned** [comment]
i can confirm the popup appears but no deadlock for me :/

**Comment by aufau** [comment]
I've tested with latest master and these steps no longer cause deadlock or incorrect download popup.
