### ISSUE TITLE
Can't create server with the last build (jk2mvded crash)

### ISSUE THREAD

**Issue by TriForceX** [mvdevs/jk2mv#99]
I dont know if i need warning about this, but in the last build (1.4-14-g521d549) jk2mvded crashes when start a server, not when open, only when when start to initialize (load a map), ive noticed when testing a mod with dll, but testing with a qvm the problem is the same. Theres no problem in the previous build (1.4-13-g73c1f52) maybe something changed is affecting that.

Theres crash details screenshots if you need them:
https://image.prntscr.com/image/vHFZNx8USc_v19s3j7H9MA.png
https://image.prntscr.com/image/diNNr_QyQz_8fKhU0x5QYg.png

**Comment by aufau** [comment]
Uh I broke something again :-(

**Comment by aufau** [comment]
Fixed in 521d54940c2d46358332dbd15cd19a22a3dd4ba7

**Comment by ouned** [comment]
he says he is using `1.4-14-g521d549` so that commit is already in his build
